
services:
  # frontend:
  #   build:
  #     context: ./frontend/
  #     dockerfile: dockerfile.frontend 
  #   image: frontend:latest
  #   ports:
  #     - "3100:3000"
  #   volumes:
  #     - ./frontend:/home/app:z
  #   command: npm start

  database:
    image: postgres:16
    ports:
      - "5450:5432"
    env_file:
      - ./database/.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:z
    restart: always
    depends_on:
      - redis
      - geoserver
  # backend:
  #   build:
  #     context: ./backend/
  #     dockerfile: docker/dockerfile.backend
  #   image: backend:latest
  #   ports:
  #     - "9200:9000"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./backend:/home/app:z
  #   command: >
  #     sh -c "python manage.py migrate &&
  #            daphne -b 0.0.0.0 -p 9000 --proxy-headers main.asgi:application"
  #   restart: always
  #   depends_on:
  #     - database
  #     - geoserver
    
  # redis_django:
  #   image: redis:7.4
  #   ports:
  #     - "6370:6379"
  #   expose:
  #     - "6370"
  #   env_file:
  #     - .env
  #   restart: always
  #   volumes:
  #     - redis_django_data:/data 

  # celery_django:
  #   build:
  #     context: ./backend/
  #     dockerfile: docker/dockerfile.backend
  #   image: celery_django:latest
  #   volumes:
  #     - ./backend:/home/app:z
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis_django
  #     - backend
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       celery -A main worker --loglevel=info -c 4 --pool=prefork --max-tasks-per-child=50


  fast_m:
    build:
      context: ./fast_m
      dockerfile: Dockerfile
    image: fast_m:latest
    ports:
      - "7100:7100"
    env_file:
      - fast_m/.fastmdb.env
    volumes:
      - ./fast_m:/home/app:z
    command: uvicorn app.main:app --host 0.0.0.0 --port 7100 --reload
    restart: always
    depends_on:
      - database
      - geoserver     
    


  fast_backend:
    build:
      context: ./fast_backend
      dockerfile: Dockerfile
    image: backend_fast:latest
    ports:
      - "7000:7000"
    env_file:
      - ./fast_backend/.fastdb.env
    volumes:
      - ./fast_backend:/home/app:z
    environment:
      - SERVICE_TYPE=app

    #command: gunicorn app.main:app --config gunicorn.conf.py --reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 7000 --reload 
    restart: always
    depends_on:
      - database
      - geoserver


  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    expose:
      - "6379"
    env_file:
      - ./fast_backend/.fastdb.env
    restart: always
    volumes:
      - redis_data:/data 

  celery_low:
    build:
      context: ./fast_backend
      dockerfile: Dockerfile
    image: celery_low:latest
    volumes:
      - ./fast_backend:/home/app:z 
    depends_on:
      - redis
      - fast_backend
      - geoserver
    environment:
      - SERVICE_TYPE=celery
    command:  
      - /bin/sh
      - -c
      - |
        celery -A app.conf.celery worker -n low_worker -c 2 --pool=prefork  -Q default  --autoscale=4,2

    env_file:
      - ./fast_backend/.fastdb.env

  celery_high:
    build:
      context: ./fast_backend
      dockerfile: Dockerfile
    image: celery_high:latest
    volumes:
      - ./fast_backend:/home/app:z 
    depends_on:
      - redis
      - fast_backend
      - geoserver
    environment:
      - SERVICE_TYPE=celery
    command:  
      - /bin/sh
      - -c
      - |
        celery -A app.conf.celery worker -n heavy_worker -c 2 --pool=prefork -Q heavy_task --autoscale=4,2

    env_file:
      - ./fast_backend/.fastdb.env
  
      
  flower:
    image: mher/flower:latest
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_low
      - celery_high
    command: celery --broker=redis://redis:6379/0 flower --port=5555

  geoserver:
    image: kartoza/geoserver:latest
    ports:
      - "9090:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - ./backend/media:/opt/geoserver/medias
    environment:
      ENABLE_CORS: "true"
      CORS_ENABLED: "true"
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE,HEAD,OPTIONS
      CORS_ALLOWED_HEADERS: "*"
      TOMCAT_EXTRAS: "true"
      HTTP_MAX_HEADER_SIZE: 33554432
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
    env_file:
      - ./fast_backend/.fastdb.env
    restart: always

volumes:
  postgres_data:
  geoserver_data:
  redis_data:
  redis_django_data: