FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/home/app


RUN echo "deb http://deb.debian.org/debian bookworm contrib" >> /etc/apt/sources.list


RUN echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections


RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    libproj-dev \
    libpq-dev \
    binutils \
    gcc \
    build-essential \
    curl \
    wget \
    ttf-mscorefonts-installer \
    fontconfig \
    && fc-cache -f -v \
    && rm -rf /var/lib/apt/lists/*


ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal
ENV GDAL_CONFIG=/usr/bin/gdal-config


WORKDIR /home/app


RUN python -m pip install --upgrade pip setuptools wheel


COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt


RUN useradd -m appuser && chown -R appuser:appuser /home/app
USER appuser

EXPOSE 7000