# Generated by Django 5.1.6 on 2025-12-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Basic_state",
            fields=[
                ("state_code", models.IntegerField(primary_key=True, serialize=False)),
                ("state_name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="BasicRunoffCoefficient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_t_minutes", models.IntegerField()),
                ("sector_impervious", models.FloatField()),
                ("sector_60percent_impervious", models.FloatField()),
                ("sector_40percent_impervious", models.FloatField()),
                ("sector_pervious", models.FloatField()),
                ("rectangle_impervious", models.FloatField()),
                ("rectangle_50percent_impervious", models.FloatField()),
                ("rectangle_30percent_impervious", models.FloatField()),
                ("rectangle_pervious", models.FloatField()),
            ],
            options={
                "db_table": "basic_runoffcoefficient",
                "ordering": ["duration_t_minutes"],
            },
        ),
        migrations.CreateModel(
            name="Population_2011",
            fields=[
                (
                    "subdistrict_code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("region_name", models.CharField(max_length=40)),
                ("population_1951", models.BigIntegerField()),
                ("population_1961", models.BigIntegerField()),
                ("population_1971", models.BigIntegerField()),
                ("population_1981", models.BigIntegerField()),
                ("population_1991", models.BigIntegerField()),
                ("population_2001", models.BigIntegerField()),
                ("population_2011", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PopulationCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.BigIntegerField()),
                ("district_code", models.BigIntegerField()),
                ("subdistrict_code", models.BigIntegerField()),
                ("village_code", models.BigIntegerField()),
                ("region_name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("age_group", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10)),
                ("population", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Basic_district",
            fields=[
                (
                    "district_code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("district_name", models.CharField(max_length=40)),
                (
                    "state_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Basic.basic_state",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Basic_subdistrict",
            fields=[
                (
                    "subdistrict_code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("subdistrict_name", models.CharField(max_length=40)),
                (
                    "district_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Basic.basic_district",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Basic_village",
            fields=[
                (
                    "village_code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("village_name", models.CharField(max_length=100)),
                ("population_2011", models.IntegerField()),
                (
                    "subdistrict_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Basic.basic_subdistrict",
                    ),
                ),
            ],
        ),
    ]
