# Generated by Django 5.1.6 on 2025-12-01 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrainWaterQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=150)),
                ("ph", models.FloatField()),
                ("temp", models.FloatField()),
                ("ec_us_cm", models.FloatField(verbose_name="EC (µS/cm)")),
                ("tds_ppm", models.FloatField(verbose_name="TDS (ppm)")),
                ("do_mg_l", models.FloatField(verbose_name="DO (mg/L)")),
                ("turbidity", models.FloatField()),
                ("tss_mg_l", models.FloatField(verbose_name="TSS (mg/L)")),
                ("cod", models.FloatField()),
                ("bod_mg_l", models.FloatField(verbose_name="BOD (mg/L)")),
                ("ts_mg_l", models.FloatField(verbose_name="TS (mg/L)")),
                ("chloride", models.FloatField()),
                ("nitrate", models.FloatField(blank=True, null=True)),
                ("faecal_col", models.CharField(blank=True, max_length=100, null=True)),
                ("total_col", models.CharField(blank=True, max_length=100, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("stream", models.CharField(blank=True, max_length=255, null=True)),
                ("observation", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "sampling_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the water sample was collected",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Drain Water Quality Data",
                "verbose_name_plural": "Drain Water Quality Data",
                "db_table": "dashboard_drainwaterquality",
                "ordering": ["-sampling_time"],
                "indexes": [
                    models.Index(
                        fields=["-sampling_time"], name="dashboard_d_samplin_fdb645_idx"
                    ),
                    models.Index(
                        fields=["location"], name="dashboard_d_locatio_02c5b3_idx"
                    ),
                    models.Index(
                        fields=["stream"], name="dashboard_d_stream_ae4e04_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryMapStation",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Unique identifier (e.g., 'station-1')",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Station location name (e.g., 'Mahadev Mandir')",
                        max_length=255,
                    ),
                ),
                (
                    "image_path",
                    models.URLField(
                        help_text="URL to station image (e.g., '/Images/dashboard/varuna1.png')",
                        max_length=500,
                    ),
                ),
                (
                    "lat",
                    models.FloatField(
                        help_text="Latitude coordinate",
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "lon",
                    models.FloatField(
                        help_text="Longitude coordinate",
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed station description"),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Additional remarks or notes about the station",
                        null=True,
                    ),
                ),
                (
                    "other",
                    models.TextField(
                        blank=True, help_text="Other information or metadata", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Map Story Station",
                "verbose_name_plural": "Map Story Stations",
                "db_table": "dashboard_mapstory",
                "ordering": ["location"],
                "indexes": [
                    models.Index(
                        fields=["location"], name="dashboard_m_locatio_66719e_idx"
                    ),
                    models.Index(
                        fields=["lat", "lon"], name="dashboard_m_lat_f5e074_idx"
                    ),
                ],
            },
        ),
    ]
