# Generated by Django 5.1.6 on 2025-09-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwa", "0003_alter_well_village_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(max_length=100)),
                ("crop", models.CharField(max_length=100)),
                ("stage", models.CharField(max_length=100)),
                ("period", models.CharField(max_length=100)),
                ("crop_factor", models.FloatField()),
            ],
        ),
    ]
