# Generated by Django 5.1.6 on 2025-10-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vlcode", models.BigIntegerField()),
                ("village", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("mon", models.IntegerField()),
                ("surq_cnt_m3", models.FloatField()),
                ("subdistrict_code_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Admin Flow",
                "verbose_name_plural": "Admin Flows",
                "db_table": "adminflow",
            },
        ),
        migrations.CreateModel(
            name="ClimateAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vlcode", models.BigIntegerField()),
                ("village", models.CharField(max_length=255)),
                ("year", models.IntegerField(db_column="YEAR")),
                ("mon", models.IntegerField(db_column="MON")),
                ("surq_cnt_m3", models.FloatField(db_column="SURQ_CNT_m3")),
                ("source_id", models.IntegerField()),
                ("subdistrict_code_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Climate Admin",
                "verbose_name_plural": "Climate Admins",
                "db_table": "climate_admin",
            },
        ),
        migrations.CreateModel(
            name="ClimateDrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub", models.IntegerField()),
                ("year", models.IntegerField()),
                ("mon", models.IntegerField()),
                ("areakm2", models.FloatField()),
                ("flow_incms", models.FloatField()),
                ("flow_outcms", models.FloatField()),
                ("yyyymm", models.IntegerField()),
                ("rch", models.IntegerField()),
            ],
            options={
                "db_table": "climate_drain",
                "indexes": [
                    models.Index(fields=["sub"], name="climate_dra_sub_1d6158_idx"),
                    models.Index(
                        fields=["year", "mon"], name="climate_dra_year_2c4b3d_idx"
                    ),
                    models.Index(
                        fields=["yyyymm"], name="climate_dra_yyyymm_f70357_idx"
                    ),
                    models.Index(fields=["rch"], name="climate_dra_rch_451c1d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubbasinFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub", models.IntegerField()),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("area_km2", models.FloatField()),
                ("flow_in_cms", models.FloatField()),
                ("flow_out_cms", models.FloatField()),
                ("yyyyddd", models.IntegerField()),
            ],
            options={
                "db_table": "subbasin_flow",
                "indexes": [
                    models.Index(fields=["sub"], name="subbasin_fl_sub_06d5d1_idx"),
                    models.Index(
                        fields=["year", "month"], name="subbasin_fl_year_68693c_idx"
                    ),
                ],
            },
        ),
    ]
