# Generated by Django 5.1.6 on 2025-12-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block", models.CharField(max_length=255)),
                ("blockcode", models.IntegerField(unique=True)),
                ("district", models.CharField(max_length=255)),
                ("districtcode", models.IntegerField()),
            ],
            options={
                "db_table": "rsq_block",
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blockcode", models.IntegerField()),
                ("vlcode", models.IntegerField(unique=True)),
                ("village", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "rsq_village",
            },
        ),
        migrations.CreateModel(
            name="GroundWaterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("village_co", models.BigIntegerField(db_index=True)),
                ("block_code", models.BigIntegerField(db_index=True)),
                ("district_code", models.FloatField(blank=True, null=True)),
                ("subdistrict_code", models.FloatField(blank=True, null=True)),
                ("year", models.CharField(db_index=True, max_length=10)),
                ("factor", models.FloatField(blank=True, null=True)),
                ("village_area", models.FloatField(blank=True, null=True)),
                ("block_area", models.FloatField(blank=True, null=True)),
                ("total_geographical_area", models.FloatField(blank=True, null=True)),
                ("recharge_worthy_area", models.FloatField(blank=True, null=True)),
                ("recharge_rainfall_mon", models.FloatField(blank=True, null=True)),
                ("recharge_other_mon", models.FloatField(blank=True, null=True)),
                ("recharge_rainfall_nm", models.FloatField(blank=True, null=True)),
                ("recharge_other_nm", models.FloatField(blank=True, null=True)),
                ("total_annual_recharge", models.FloatField(blank=True, null=True)),
                ("total_natural_discharge", models.FloatField(blank=True, null=True)),
                ("extractable_resource", models.FloatField(blank=True, null=True)),
                ("irrigation_use", models.FloatField(blank=True, null=True)),
                ("industrial_use", models.FloatField(blank=True, null=True)),
                ("domestic_use", models.FloatField(blank=True, null=True)),
                ("total_extraction", models.FloatField(blank=True, null=True)),
                (
                    "annual_gw_allocation_domestic",
                    models.FloatField(blank=True, null=True),
                ),
                ("net_future_availability", models.FloatField(blank=True, null=True)),
                ("bo_aquifer", models.FloatField(blank=True, null=True)),
                (
                    "stage_of_extraction",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "village_groundwater",
                "indexes": [
                    models.Index(
                        fields=["village_co", "year"],
                        name="village_gro_village_8c46ed_idx",
                    ),
                    models.Index(
                        fields=["block_code"], name="village_gro_block_c_81f003_idx"
                    ),
                ],
            },
        ),
    ]
