"""updation

Revision ID: de1d23b99362
Revises: 
Create Date: 2026-03-14 10:58:17.288584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1d23b99362'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WA_stretches',
    sa.Column('Stretch_ID', sa.Integer(), nullable=False),
    sa.Column('River_Code', sa.Integer(), nullable=False),
    sa.Column('GRID_CODE', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('Stretch_ID')
    )
    op.create_table('adminflow',
    sa.Column('vlcode', sa.BigInteger(), nullable=False),
    sa.Column('village', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mon', sa.Integer(), nullable=False),
    sa.Column('surq_cnt_m3', sa.Float(), nullable=False),
    sa.Column('subdistrict_code_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminflow_id'), 'adminflow', ['id'], unique=True)
    op.create_table('basic_basic_state',
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('state_code')
    )
    op.create_table('basic_population_2011',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(length=40), nullable=False),
    sa.Column('population_1951', sa.BigInteger(), nullable=False),
    sa.Column('population_1961', sa.BigInteger(), nullable=False),
    sa.Column('population_1971', sa.BigInteger(), nullable=False),
    sa.Column('population_1981', sa.BigInteger(), nullable=False),
    sa.Column('population_1991', sa.BigInteger(), nullable=False),
    sa.Column('population_2001', sa.BigInteger(), nullable=False),
    sa.Column('population_2011', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('subdistrict_code')
    )
    op.create_table('basic_populationcohort',
    sa.Column('state_code', sa.BigInteger(), nullable=False),
    sa.Column('district_code', sa.BigInteger(), nullable=False),
    sa.Column('subdistrict_code', sa.BigInteger(), nullable=False),
    sa.Column('village_code', sa.BigInteger(), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_populationcohort_id'), 'basic_populationcohort', ['id'], unique=True)
    op.create_table('basic_runoffcoefficient',
    sa.Column('duration_t_minutes', sa.Integer(), nullable=False),
    sa.Column('sector_impervious', sa.Float(), nullable=False),
    sa.Column('sector_60percent_impervious', sa.Float(), nullable=False),
    sa.Column('sector_40percent_impervious', sa.Float(), nullable=False),
    sa.Column('sector_pervious', sa.Float(), nullable=False),
    sa.Column('rectangle_impervious', sa.Float(), nullable=False),
    sa.Column('rectangle_50percent_impervious', sa.Float(), nullable=False),
    sa.Column('rectangle_30percent_impervious', sa.Float(), nullable=False),
    sa.Column('rectangle_pervious', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_runoffcoefficient_id'), 'basic_runoffcoefficient', ['id'], unique=True)
    op.create_table('climate_admin',
    sa.Column('vlcode', sa.BigInteger(), nullable=False),
    sa.Column('village', sa.String(length=255), nullable=False),
    sa.Column('YEAR', sa.Integer(), nullable=False),
    sa.Column('MON', sa.Integer(), nullable=False),
    sa.Column('SURQ_CNT_m3', sa.Float(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('subdistrict_code_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_admin_id'), 'climate_admin', ['id'], unique=True)
    op.create_table('climate_drain',
    sa.Column('sub', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mon', sa.Integer(), nullable=False),
    sa.Column('areakm2', sa.Float(), nullable=False),
    sa.Column('flow_incms', sa.Float(), nullable=False),
    sa.Column('flow_outcms', sa.Float(), nullable=False),
    sa.Column('yyyymm', sa.Integer(), nullable=False),
    sa.Column('rch', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_drain_id'), 'climate_drain', ['id'], unique=True)
    op.create_index('ix_climate_drain_rch', 'climate_drain', ['rch'], unique=False)
    op.create_index('ix_climate_drain_sub', 'climate_drain', ['sub'], unique=False)
    op.create_index('ix_climate_drain_year_mon', 'climate_drain', ['year', 'mon'], unique=False)
    op.create_index('ix_climate_drain_yyyymm', 'climate_drain', ['yyyymm'], unique=False)
    op.create_table('gwa_crop',
    sa.Column('season', sa.String(length=100), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=100), nullable=False),
    sa.Column('crop_factor', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwa_crop_id'), 'gwa_crop', ['id'], unique=True)
    op.create_table('gwa_population_2011',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(length=40), nullable=False),
    sa.Column('population_1951', sa.BigInteger(), nullable=False),
    sa.Column('population_1961', sa.BigInteger(), nullable=False),
    sa.Column('population_1971', sa.BigInteger(), nullable=False),
    sa.Column('population_1981', sa.BigInteger(), nullable=False),
    sa.Column('population_1991', sa.BigInteger(), nullable=False),
    sa.Column('population_2001', sa.BigInteger(), nullable=False),
    sa.Column('population_2011', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('subdistrict_code')
    )
    op.create_index(op.f('ix_gwa_population_2011_subdistrict_code'), 'gwa_population_2011', ['subdistrict_code'], unique=False)
    op.create_table('gwa_state',
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state_code')
    )
    op.create_index(op.f('ix_gwa_state_state_code'), 'gwa_state', ['state_code'], unique=False)
    op.create_table('stp_state',
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state_code', 'id'),
    sa.UniqueConstraint('state_code')
    )
    op.create_index(op.f('ix_stp_state_id'), 'stp_state', ['id'], unique=True)
    op.create_table('subbasin_flow',
    sa.Column('sub', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('flow_in_cms', sa.Float(), nullable=False),
    sa.Column('flow_out_cms', sa.Float(), nullable=False),
    sa.Column('yyyyddd', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subbasin_flow_id'), 'subbasin_flow', ['id'], unique=True)
    op.create_index('ix_subbasin_flow_sub', 'subbasin_flow', ['sub'], unique=False)
    op.create_index('ix_subbasin_flow_year_month', 'subbasin_flow', ['year', 'month'], unique=False)
    op.create_table('WA_drain',
    sa.Column('River_Code', sa.Integer(), nullable=False),
    sa.Column('Drain_No', sa.Integer(), nullable=False),
    sa.Column('Stretch_ID', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Stretch_ID'], ['WA_stretches.Stretch_ID'], ),
    sa.PrimaryKeyConstraint('Drain_No', 'Stretch_ID')
    )
    op.create_table('basic_basic_district',
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=40), nullable=False),
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['basic_basic_state.state_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('district_code')
    )
    op.create_index(op.f('ix_basic_basic_district_state_code'), 'basic_basic_district', ['state_code'], unique=False)
    op.create_table('gwa_district',
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=40), nullable=False),
    sa.Column('state_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['gwa_state.state_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('district_code')
    )
    op.create_index(op.f('ix_gwa_district_district_code'), 'gwa_district', ['district_code'], unique=False)
    op.create_table('stp_district',
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(), nullable=False),
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['stp_state.state_code'], ),
    sa.PrimaryKeyConstraint('district_code', 'id'),
    sa.UniqueConstraint('district_code')
    )
    op.create_index(op.f('ix_stp_district_id'), 'stp_district', ['id'], unique=True)
    op.create_table('basic_basic_subdistrict',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('subdistrict_name', sa.String(length=40), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['basic_basic_district.district_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subdistrict_code')
    )
    op.create_index(op.f('ix_basic_basic_subdistrict_district_code'), 'basic_basic_subdistrict', ['district_code'], unique=False)
    op.create_table('gwa_subdistrict',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('subdistrict_name', sa.String(length=40), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['gwa_district.district_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subdistrict_code')
    )
    op.create_index(op.f('ix_gwa_subdistrict_subdistrict_code'), 'gwa_subdistrict', ['subdistrict_code'], unique=False)
    op.create_table('stp_subdistrict',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('subdistrict_name', sa.String(), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['stp_district.district_code'], ),
    sa.PrimaryKeyConstraint('subdistrict_code', 'id'),
    sa.UniqueConstraint('subdistrict_code')
    )
    op.create_index(op.f('ix_stp_subdistrict_id'), 'stp_subdistrict', ['id'], unique=True)
    op.create_table('basic_basic_village',
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(length=100), nullable=False),
    sa.Column('population_2011', sa.Integer(), nullable=False),
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['basic_basic_subdistrict.subdistrict_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('village_code')
    )
    op.create_index(op.f('ix_basic_basic_village_subdistrict_code'), 'basic_basic_village', ['subdistrict_code'], unique=False)
    op.create_table('gwa_village',
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(length=100), nullable=False),
    sa.Column('population_2011', sa.Integer(), nullable=False),
    sa.Column('subdistrict_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['gwa_subdistrict.subdistrict_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('village_code')
    )
    op.create_index(op.f('ix_gwa_village_village_code'), 'gwa_village', ['village_code'], unique=False)
    op.create_table('stp_towns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classs', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['stp_subdistrict.subdistrict_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('stp_villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(), nullable=False),
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['stp_subdistrict.subdistrict_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('gwa_well',
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('FID_clip', sa.Integer(), nullable=True),
    sa.Column('OBJECTID', sa.Integer(), nullable=True),
    sa.Column('shapeName', sa.String(length=100), nullable=True),
    sa.Column('SUB_DISTRI', sa.String(length=100), nullable=True),
    sa.Column('DISTRICT_C', sa.Integer(), nullable=True),
    sa.Column('DISTRICT', sa.String(length=100), nullable=True),
    sa.Column('STATE_CODE', sa.Integer(), nullable=True),
    sa.Column('STATE', sa.String(length=100), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('SUBDIS_COD', sa.Integer(), nullable=True),
    sa.Column('Area', sa.Float(), nullable=True),
    sa.Column('DISTRICT_1', sa.String(length=100), nullable=True),
    sa.Column('BLOCK', sa.String(length=100), nullable=True),
    sa.Column('HYDROGRAPH', sa.String(length=100), nullable=True),
    sa.Column('LONGITUDE', sa.Float(), nullable=True),
    sa.Column('LATITUDE', sa.Float(), nullable=True),
    sa.Column('RL', sa.Float(), nullable=True),
    sa.Column('PRE_2011', sa.Float(), nullable=True),
    sa.Column('POST_2011', sa.Float(), nullable=True),
    sa.Column('PRE_2012', sa.Float(), nullable=True),
    sa.Column('POST_2012', sa.Float(), nullable=True),
    sa.Column('PRE_2013', sa.Float(), nullable=True),
    sa.Column('POST_2013', sa.Float(), nullable=True),
    sa.Column('PRE_2014', sa.Float(), nullable=True),
    sa.Column('POST_2014', sa.Float(), nullable=True),
    sa.Column('PRE_2015', sa.Float(), nullable=True),
    sa.Column('POST_2015', sa.Float(), nullable=True),
    sa.Column('PRE_2016', sa.Float(), nullable=True),
    sa.Column('POST_2016', sa.Float(), nullable=True),
    sa.Column('PRE_2017', sa.Float(), nullable=True),
    sa.Column('POST_2017', sa.Float(), nullable=True),
    sa.Column('PRE_2018', sa.Float(), nullable=True),
    sa.Column('POST_2018', sa.Float(), nullable=True),
    sa.Column('PRE_2019', sa.Float(), nullable=True),
    sa.Column('POST_2019', sa.Float(), nullable=True),
    sa.Column('PRE_2020', sa.Float(), nullable=True),
    sa.Column('POST_2020', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['village_code'], ['gwa_village.village_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('FID_clip')
    )
    op.create_index(op.f('ix_gwa_well_id'), 'gwa_well', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gwa_well_id'), table_name='gwa_well')
    op.drop_table('gwa_well')
    op.drop_table('stp_villages')
    op.drop_table('stp_towns')
    op.drop_index(op.f('ix_gwa_village_village_code'), table_name='gwa_village')
    op.drop_table('gwa_village')
    op.drop_index(op.f('ix_basic_basic_village_subdistrict_code'), table_name='basic_basic_village')
    op.drop_table('basic_basic_village')
    op.drop_index(op.f('ix_stp_subdistrict_id'), table_name='stp_subdistrict')
    op.drop_table('stp_subdistrict')
    op.drop_index(op.f('ix_gwa_subdistrict_subdistrict_code'), table_name='gwa_subdistrict')
    op.drop_table('gwa_subdistrict')
    op.drop_index(op.f('ix_basic_basic_subdistrict_district_code'), table_name='basic_basic_subdistrict')
    op.drop_table('basic_basic_subdistrict')
    op.drop_index(op.f('ix_stp_district_id'), table_name='stp_district')
    op.drop_table('stp_district')
    op.drop_index(op.f('ix_gwa_district_district_code'), table_name='gwa_district')
    op.drop_table('gwa_district')
    op.drop_index(op.f('ix_basic_basic_district_state_code'), table_name='basic_basic_district')
    op.drop_table('basic_basic_district')
    op.drop_table('WA_drain')
    op.drop_index('ix_subbasin_flow_year_month', table_name='subbasin_flow')
    op.drop_index('ix_subbasin_flow_sub', table_name='subbasin_flow')
    op.drop_index(op.f('ix_subbasin_flow_id'), table_name='subbasin_flow')
    op.drop_table('subbasin_flow')
    op.drop_index(op.f('ix_stp_state_id'), table_name='stp_state')
    op.drop_table('stp_state')
    op.drop_index(op.f('ix_gwa_state_state_code'), table_name='gwa_state')
    op.drop_table('gwa_state')
    op.drop_index(op.f('ix_gwa_population_2011_subdistrict_code'), table_name='gwa_population_2011')
    op.drop_table('gwa_population_2011')
    op.drop_index(op.f('ix_gwa_crop_id'), table_name='gwa_crop')
    op.drop_table('gwa_crop')
    op.drop_index('ix_climate_drain_yyyymm', table_name='climate_drain')
    op.drop_index('ix_climate_drain_year_mon', table_name='climate_drain')
    op.drop_index('ix_climate_drain_sub', table_name='climate_drain')
    op.drop_index('ix_climate_drain_rch', table_name='climate_drain')
    op.drop_index(op.f('ix_climate_drain_id'), table_name='climate_drain')
    op.drop_table('climate_drain')
    op.drop_index(op.f('ix_climate_admin_id'), table_name='climate_admin')
    op.drop_table('climate_admin')
    op.drop_index(op.f('ix_basic_runoffcoefficient_id'), table_name='basic_runoffcoefficient')
    op.drop_table('basic_runoffcoefficient')
    op.drop_index(op.f('ix_basic_populationcohort_id'), table_name='basic_populationcohort')
    op.drop_table('basic_populationcohort')
    op.drop_table('basic_population_2011')
    op.drop_table('basic_basic_state')
    op.drop_index(op.f('ix_adminflow_id'), table_name='adminflow')
    op.drop_table('adminflow')
    op.drop_table('WA_stretches')
    # ### end Alembic commands ###
