"""make_report

Revision ID: 62a384b94586
Revises: df5c6272a378
Create Date: 2025-07-26 21:54:52.718439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a384b94586'
down_revision: Union[str, None] = 'df5c6272a378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_reports',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_reports_id'), 'email_reports', ['id'], unique=True)
    op.create_unique_constraint(None, 'stp_catchment', ['id'])
    op.create_unique_constraint(None, 'stp_towns', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stp_towns', type_='unique')
    op.drop_constraint(None, 'stp_catchment', type_='unique')
    op.drop_index(op.f('ix_email_reports_id'), table_name='email_reports')
    op.drop_table('email_reports')
    # ### end Alembic commands ###
