"""new update 

Revision ID: efe3beba3588
Revises: 
Create Date: 2026-03-14 04:44:51.211902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efe3beba3588'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GWQI_param_Index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celery_task',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_status', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('layer_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_celery_task_id'), 'celery_task', ['id'], unique=False)
    op.create_table('groundwater_Identification_visual',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('sld_path', sa.String(), nullable=False),
    sa.Column('raster_category', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groundwater_Identification_visual_id'), 'groundwater_Identification_visual', ['id'], unique=False)
    op.create_table('groundwater_identification_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('raster_category', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groundwater_identification_raster_id'), 'groundwater_identification_raster', ['id'], unique=False)
    op.create_table('groundwater_zone_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groundwater_zone_raster_id'), 'groundwater_zone_raster', ['id'], unique=False)
    op.create_table('groundwater_zone_visual_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('sld_path', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groundwater_zone_visual_raster_id'), 'groundwater_zone_visual_raster', ['id'], unique=False)
    op.create_table('mar_raster_details',
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mar_raster_details_id'), 'mar_raster_details', ['id'], unique=False)
    op.create_table('mar_suitability_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('raster_category', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('needed', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mar_suitability_raster_id'), 'mar_suitability_raster', ['id'], unique=False)
    op.create_table('mar_suitability_visual_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('sld_path', sa.String(), nullable=False),
    sa.Column('raster_category', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mar_suitability_visual_raster_id'), 'mar_suitability_visual_raster', ['id'], unique=False)
    op.create_table('rainwater_raster',
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('layer_month', sa.Integer(), nullable=False),
    sa.Column('layer_class', sa.String(), nullable=False),
    sa.Column('sld_path', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rainwater_raster_id'), 'rainwater_raster', ['id'], unique=False)
    op.create_table('raster_storage',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('raster_type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['raster_storage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_raster_storage_id'), 'raster_storage', ['id'], unique=False)
    op.create_table('stp_priority_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stp_priority_raster_id'), 'stp_priority_raster', ['id'], unique=False)
    op.create_table('stp_priority_visual_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('sld_path', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stp_priority_visual_raster_id'), 'stp_priority_visual_raster', ['id'], unique=False)
    op.create_table('stp_river',
    sa.Column('River_Code', sa.Integer(), nullable=False),
    sa.Column('River_Name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('River_Code', 'id'),
    sa.UniqueConstraint('River_Code')
    )
    op.create_index(op.f('ix_stp_river_id'), 'stp_river', ['id'], unique=False)
    op.create_table('stp_state',
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state_code', 'id'),
    sa.UniqueConstraint('state_code')
    )
    op.create_index(op.f('ix_stp_state_id'), 'stp_state', ['id'], unique=False)
    op.create_table('stp_suitability_area',
    sa.Column('tech_name', sa.String(), nullable=False),
    sa.Column('tech_value', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stp_suitability_area_id'), 'stp_suitability_area', ['id'], unique=False)
    op.create_table('stp_suitability_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('raster_category', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stp_suitability_raster_id'), 'stp_suitability_raster', ['id'], unique=False)
    op.create_table('stp_suitability_visual_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('sld_path', sa.String(), nullable=False),
    sa.Column('raster_category', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stp_suitability_visual_raster_id'), 'stp_suitability_visual_raster', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('water_quality_assessment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Location', sa.String(), nullable=False),
    sa.Column('Longitude', sa.Float(), nullable=False),
    sa.Column('Latitude', sa.Float(), nullable=False),
    sa.Column('pH_Level', sa.Float(), nullable=False),
    sa.Column('Electrical_Conductivity', sa.Float(), nullable=False),
    sa.Column('Carbonate', sa.Float(), nullable=False),
    sa.Column('Bicarbonate', sa.Float(), nullable=False),
    sa.Column('Chloride', sa.Float(), nullable=False),
    sa.Column('Fluoride', sa.Float(), nullable=False),
    sa.Column('Sulfate', sa.Float(), nullable=False),
    sa.Column('Nitrate', sa.Float(), nullable=False),
    sa.Column('Hardness', sa.Float(), nullable=False),
    sa.Column('Calcium', sa.Float(), nullable=False),
    sa.Column('Magnesium', sa.Float(), nullable=False),
    sa.Column('Sodium', sa.Float(), nullable=False),
    sa.Column('Potassium', sa.Float(), nullable=False),
    sa.Column('Iron', sa.Float(), nullable=False),
    sa.Column('Arsenic', sa.Float(), nullable=False),
    sa.Column('Uranium', sa.Float(), nullable=False),
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('subdis_code', sa.Integer(), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_reports',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_reports_id'), 'email_reports', ['id'], unique=False)
    op.create_table('raster_metadata',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('driver', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('band_count', sa.Integer(), nullable=False),
    sa.Column('dtypes', sa.String(), nullable=False),
    sa.Column('nodata', sa.Float(), nullable=True),
    sa.Column('crs', sa.String(), nullable=False),
    sa.Column('crs_unit', sa.String(), nullable=False),
    sa.Column('compression', sa.String(), nullable=True),
    sa.Column('is_tiled', sa.Boolean(), nullable=False),
    sa.Column('block_shapes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_cog_like', sa.Boolean(), nullable=False),
    sa.Column('file_size', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('bounds', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('bounds_wgs84', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('bands', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['raster_storage.file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_raster_metadata_id'), 'raster_metadata', ['id'], unique=False)
    op.create_table('stp_district',
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(), nullable=False),
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['stp_state.state_code'], ),
    sa.PrimaryKeyConstraint('district_code', 'id'),
    sa.UniqueConstraint('district_code')
    )
    op.create_index(op.f('ix_stp_district_id'), 'stp_district', ['id'], unique=False)
    op.create_table('stp_stretches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Stretch_ID', sa.Integer(), nullable=False),
    sa.Column('river_Code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['river_Code'], ['stp_river.River_Code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_no', sa.String(length=15), nullable=False),
    sa.Column('organisation', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('stp_drain',
    sa.Column('Drain_No', sa.Integer(), nullable=False),
    sa.Column('stretch_id', sa.Integer(), nullable=False),
    sa.Column('River_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stretch_id'], ['stp_stretches.id'], ),
    sa.PrimaryKeyConstraint('Drain_No', 'id'),
    sa.UniqueConstraint('Drain_No')
    )
    op.create_index(op.f('ix_stp_drain_id'), 'stp_drain', ['id'], unique=False)
    op.create_table('stp_drain_suitability',
    sa.Column('Drain_No', sa.Integer(), nullable=False),
    sa.Column('stretch_id', sa.Integer(), nullable=False),
    sa.Column('River_code', sa.Integer(), nullable=False),
    sa.Column('drain_class', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Drain_Area', sa.Float(), nullable=False),
    sa.Column('Elevation', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stretch_id'], ['stp_stretches.id'], ),
    sa.PrimaryKeyConstraint('Drain_No', 'id'),
    sa.UniqueConstraint('Drain_No')
    )
    op.create_index(op.f('ix_stp_drain_suitability_id'), 'stp_drain_suitability', ['id'], unique=False)
    op.create_table('stp_subdistrict',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('subdistrict_name', sa.String(), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['stp_district.district_code'], ),
    sa.PrimaryKeyConstraint('subdistrict_code', 'id'),
    sa.UniqueConstraint('subdistrict_code')
    )
    op.create_index(op.f('ix_stp_subdistrict_id'), 'stp_subdistrict', ['id'], unique=False)
    op.create_table('stp_catchment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('GRIDCODE', sa.Integer(), nullable=False),
    sa.Column('Drain_No', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Drain_No'], ['stp_drain.Drain_No'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('stp_towns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classs', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['stp_subdistrict.subdistrict_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('stp_villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(), nullable=False),
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['stp_subdistrict.subdistrict_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stp_villages')
    op.drop_table('stp_towns')
    op.drop_table('stp_catchment')
    op.drop_index(op.f('ix_stp_subdistrict_id'), table_name='stp_subdistrict')
    op.drop_table('stp_subdistrict')
    op.drop_index(op.f('ix_stp_drain_suitability_id'), table_name='stp_drain_suitability')
    op.drop_table('stp_drain_suitability')
    op.drop_index(op.f('ix_stp_drain_id'), table_name='stp_drain')
    op.drop_table('stp_drain')
    op.drop_table('user_details')
    op.drop_table('stp_stretches')
    op.drop_index(op.f('ix_stp_district_id'), table_name='stp_district')
    op.drop_table('stp_district')
    op.drop_index(op.f('ix_raster_metadata_id'), table_name='raster_metadata')
    op.drop_table('raster_metadata')
    op.drop_index(op.f('ix_email_reports_id'), table_name='email_reports')
    op.drop_table('email_reports')
    op.drop_table('water_quality_assessment')
    op.drop_table('users')
    op.drop_index(op.f('ix_stp_suitability_visual_raster_id'), table_name='stp_suitability_visual_raster')
    op.drop_table('stp_suitability_visual_raster')
    op.drop_index(op.f('ix_stp_suitability_raster_id'), table_name='stp_suitability_raster')
    op.drop_table('stp_suitability_raster')
    op.drop_index(op.f('ix_stp_suitability_area_id'), table_name='stp_suitability_area')
    op.drop_table('stp_suitability_area')
    op.drop_index(op.f('ix_stp_state_id'), table_name='stp_state')
    op.drop_table('stp_state')
    op.drop_index(op.f('ix_stp_river_id'), table_name='stp_river')
    op.drop_table('stp_river')
    op.drop_index(op.f('ix_stp_priority_visual_raster_id'), table_name='stp_priority_visual_raster')
    op.drop_table('stp_priority_visual_raster')
    op.drop_index(op.f('ix_stp_priority_raster_id'), table_name='stp_priority_raster')
    op.drop_table('stp_priority_raster')
    op.drop_index(op.f('ix_raster_storage_id'), table_name='raster_storage')
    op.drop_table('raster_storage')
    op.drop_index(op.f('ix_rainwater_raster_id'), table_name='rainwater_raster')
    op.drop_table('rainwater_raster')
    op.drop_index(op.f('ix_mar_suitability_visual_raster_id'), table_name='mar_suitability_visual_raster')
    op.drop_table('mar_suitability_visual_raster')
    op.drop_index(op.f('ix_mar_suitability_raster_id'), table_name='mar_suitability_raster')
    op.drop_table('mar_suitability_raster')
    op.drop_index(op.f('ix_mar_raster_details_id'), table_name='mar_raster_details')
    op.drop_table('mar_raster_details')
    op.drop_index(op.f('ix_groundwater_zone_visual_raster_id'), table_name='groundwater_zone_visual_raster')
    op.drop_table('groundwater_zone_visual_raster')
    op.drop_index(op.f('ix_groundwater_zone_raster_id'), table_name='groundwater_zone_raster')
    op.drop_table('groundwater_zone_raster')
    op.drop_index(op.f('ix_groundwater_identification_raster_id'), table_name='groundwater_identification_raster')
    op.drop_table('groundwater_identification_raster')
    op.drop_index(op.f('ix_groundwater_Identification_visual_id'), table_name='groundwater_Identification_visual')
    op.drop_table('groundwater_Identification_visual')
    op.drop_index(op.f('ix_celery_task_id'), table_name='celery_task')
    op.drop_table('celery_task')
    op.drop_table('GWQI_param_Index')
    # ### end Alembic commands ###
